### ISSUE TITLE
Number on track imported from Cozic

### ISSUE THREAD

**Issue by clochix** [cozy-labs/cozy-music#63]
A user reports than [when he imports tracks from Cozic](https://forum.cozy.io/t/cozy-music-et-cozic-ne-marchent-plus-correctement/2626/11), they are prefixed with a number but some numbers are missing.

**Comment by Cemoi-71** [comment]
sorry, that is a wrong alarm triggered from me.
music generate no prefixed number to display on the list of the gui.
Was a wrong interpretation from me after a usage of difference tools to put my file on cozy system.
If someone may close it, because i'm not able to do it.
Sorry for the inconvenience.
