### ISSUE TITLE
Bad url displayed in 'MyApps'

### ISSUE THREAD

**Issue by dkm** [cozy-labs/cozy-music#64]
After installing 'Music' from the 'Store', the URL displayed for the app in 'My Apps' is truncated to : 
`https://github.com/cozy-labs/cozy-m(master)`

Clicking the link ends up on 404.

**Comment by dkm** [comment]
I can install the 0.4.3 version using the correct URL. Maybe it is linked to #57 where I can't see the fix as an update.

**Comment by flyingrub** [comment]
you need to install using the build branch : `https://github.com/cozy-labs/cozy-music.git@build`

**Comment by dkm** [comment]
Ok.... but still, when installing using the store, the URL displayed is wrong and points to 404.

**Comment by dkm** [comment]
Oh, and using the link above installs the 0.4.1... that's a bit disappointing.

**Comment by flyingrub** [comment]
@m4dz Can you enlight us on the way cozy-music is now build ?

**Comment by m4dz** [comment]
@flyingrub sure :smile: !

The app is now distributed via NPM (which is our new process) instead of using a `git clone` of the repo.

We had enabled npm auto-publish from Travis when we tag a release from the `master` branch. Unfortunately, it seems Travis has changed its way of binding npm publish, deployment fails from Travis.

So, here's the process:

*\* build**

You still have a `npm run build` task which build a clean version of the app in the `public` (uncommited) folder.

**publish**
1. when merging into the `master` branch, Travis handles the merge, makes a build (using the npm task) on its way, and then push the content of the freshly-generated `public` dir into the `build` branch. So this last one always reflect a fresh build from the master (and can be manually installed from the market with the `@build` branch syntax).
2. we tag the version on this `build` branch (preferably using the git `-s` sign syntax to verify the version tag, and then deploy the tag manually to npm.

I'll report this into the Readme file :wink:

**Comment by jsilvestre** [comment]
Are we good on this one?

**Comment by m4dz** [comment]
@jsilvestre I'll take a look at it

**Comment by m4dz** [comment]
I can't repoduce, it seems to be fixed 🎉
